[repository]
name = "HyprTracker"
authors = ["NuttyShrimp"]
commit_pins = [
  ["71a1216abcc7031776630a6d88f105605c4dc1c9", "65c168238207e4ead5be168eb7697dd929e2f0fa"]
]

[hyprtracker]
description = "A plugin to track your time spending in applications"
authors = ["NuttyShrimp"]
output = "plugin/build/meson-src/libhyprtracker.so"
build = [
    "make -C plugin compile"
]
